[package]
name = "lighthouse-client"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
websocket = "0.26"
log = "0.4"
rmp-serde = "1.0"
