[package]
name = "lighthouse-client"
description = "API client for a light installation at the University of Kiel"
version = "0.1.0"
edition = "2021"
categories = ["api-bindings", "asynchronous"]
repository = "https://github.com/fwcd/lighthouse-rust"
license = "MIT"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
async-std = "1.10" # TODO: Make the library agnostic of the async runtime
async-tungstenite = { version = "0.16", features = ["async-std-runtime", "async-native-tls"] }
futures = "0.3"
tracing = "0.1"
serde = { version = "1.0", features = ["derive"] }
serde_with = "1.12"
rmp-serde = "1.0"
rand = "0.8"

[dev-dependencies]
tracing-subscriber = "0.3"
