[package]
name = "lighthouse-client"
description = "API client for a light installation at the University of Kiel"
version = "0.4.1"
edition = "2021"
categories = ["api-bindings", "asynchronous"]
repository = "https://github.com/fwcd/lighthouse-rust"
license = "MIT"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[features]
default = []
async-std = ["dep:async-std", "async-tungstenite/async-std-runtime", "async-tungstenite/async-native-tls"]
tokio = ["dep:tokio", "async-tungstenite/tokio-runtime", "async-tungstenite/tokio-native-tls"]

[dependencies]
async-std = { version = "1.10", features = ["attributes"], optional = true }
tokio = { version = "1.21", features = ["rt"], optional = true }
async-tungstenite = { version = "0.17", features = [] }
futures = "0.3"
tracing = "0.1"
serde = { version = "1.0", features = ["derive"] }
serde_with = "2.0"
rmp-serde = "1.0"
rand = "0.8"

[dev-dependencies]
tracing-subscriber = { version = "0.3", features = ["env-filter", "std"] }

[[example]]
name = "disco"
required-features = ["async-std"]

[[example]]
name = "input_events"
required-features = ["async-std"]

[[example]]
name = "snake"
required-features = ["async-std"]
