[package]
name = "lighthouse-client"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
async-tungstenite = "0.16"
log = "0.4"
rmp-serde = "1.0"

[dev-dependencies]
async-std = "1.10"
