[package]
name = "lighthouse-client"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
async-std = "1.10" # TODO: Make the library agnostic of the async runtime
async-tungstenite = { version = "0.16", features = ["async-std-runtime"] }
log = "0.4"
serde = { version = "1.0", features = ["derive"] }
rmp-serde = "1.0"
