[workspace]
members = [
    "lighthouse-client",
    "lighthouse-protocol",
]
default-members = ["lighthouse-client"]
resolver = "2"

[workspace.package]
version = "5.0.4"
edition = "2021"
license = "MIT"

[workspace.dependencies]
lighthouse-protocol = { version = "^5.0.4", path = "lighthouse-protocol" }
