use serde::{Deserialize, Serialize};

use crate::Direction;

use super::{EventSource, GamepadControlEvent, GamepadEvent, KeyEvent, MouseEvent};

/// A user input event, as generated by the new frontend (LUNA).
#[derive(Debug, Serialize, Deserialize, PartialEq, Clone)]
#[serde(tag = "type", rename_all = "camelCase")]
pub enum InputEvent {
    Key(KeyEvent),
    Mouse(MouseEvent),
    Gamepad(GamepadEvent),
}

impl InputEvent {
    /// The event's source.
    pub fn source(&self) -> &EventSource {
        match self {
            InputEvent::Key(KeyEvent { source, .. }) => source,
            InputEvent::Mouse(MouseEvent { source, .. }) => source,
            InputEvent::Gamepad(GamepadEvent { source, .. }) => source,
        }
    }

    /// Parses the input event as an arbitrary direction.
    pub fn direction(&self) -> Option<Direction> {
        self.left_direction().or_else(|| self.right_direction())
    }

    /// The direction if the input event represents a WASD key, D-pad or left stick.
    /// Commonly used e.g. for movement in games.
    pub fn left_direction(&self) -> Option<Direction> {
        match self {
            InputEvent::Key(key) => key.wasd_direction(),
            InputEvent::Gamepad(gamepad) => match &gamepad.control {
                GamepadControlEvent::Button(button) => button.d_pad_direction(),
                GamepadControlEvent::Axis2D(axis2d) if axis2d.index == 0 => axis2d.direction(),
                _ => None,
            },
            _ => None,
        }
    }

    /// The direction if the input event represents an arrow key or right stick.
    /// Commonly used e.g. for camera control in games.
    pub fn right_direction(&self) -> Option<Direction> {
        match self {
            InputEvent::Key(key) => key.arrow_direction(),
            InputEvent::Gamepad(gamepad) => match &gamepad.control {
                GamepadControlEvent::Axis2D(axis2d) if axis2d.index == 1 => axis2d.direction(),
                _ => None,
            },
            _ => None,
        }
    }
}

#[cfg(test)]
mod tests {
    use serde_json::json;

    use crate::{EventSource, GamepadAxis2DEvent, GamepadAxisEvent, GamepadButtonEvent, GamepadControlEvent, GamepadEvent, InputEvent, KeyEvent, KeyModifiers, MouseButton, MouseEvent, Pos, Vec2};

    #[test]
    fn key_event() {
        assert_eq!(
            serde_json::from_value::<InputEvent>(json!({
                "type": "key",
                "source": 0,
                "down": true,
                "repeat": false,
                "code": "ArrowUp",
                "modifiers": {
                    "alt": false,
                    "ctrl": false,
                    "meta": false,
                    "shift": false,
                },
            })).unwrap(),
            InputEvent::Key(KeyEvent {
                source: EventSource::Int(0),
                down: true,
                repeat: false,
                code: "ArrowUp".into(),
                modifiers: KeyModifiers::default(),
            })
        );
    }

    #[test]
    fn mouse_event() {
        assert_eq!(
            serde_json::from_value::<InputEvent>(json!({
                "type": "mouse",
                "source": 1,
                "button": "left",
                "pos": {
                    "x": 2,
                    "y": 4,
                },
            })).unwrap(),
            InputEvent::Mouse(MouseEvent {
                source: EventSource::Int(1),
                button: MouseButton::Left,
                pos: Pos::new(2.0, 4.0),
            })
        );
    }

    #[test]
    fn gamepad_button_event() {
        assert_eq!(
            serde_json::from_value::<InputEvent>(json!({
                "type": "gamepad",
                "source": 1,
                "control": "button",
                "index": 42,
                "down": true,
                "value": 0.25,
            })).unwrap(),
            InputEvent::Gamepad(GamepadEvent {
                source: EventSource::Int(1),
                control: GamepadControlEvent::Button(GamepadButtonEvent {
                    index: 42,
                    down: true,
                    value: 0.25,
                }),
            })
        );
    }

    #[test]
    fn gamepad_axis_event() {
        assert_eq!(
            serde_json::from_value::<InputEvent>(json!({
                "type": "gamepad",
                "source": 1,
                "control": "axis",
                "index": 42,
                "value": 0.25,
            })).unwrap(),
            InputEvent::Gamepad(GamepadEvent {
                source: EventSource::Int(1),
                control: GamepadControlEvent::Axis(GamepadAxisEvent {
                    index: 42,
                    value: 0.25,
                }),
            })
        );
    }

    #[test]
    fn gamepad_axis_2d_event() {
        assert_eq!(
            serde_json::from_value::<InputEvent>(json!({
                "type": "gamepad",
                "source": 1,
                "control": "axis2d",
                "index": 42,
                "value": {
                    "x": 0.2,
                    "y": -0.2,
                },
            })).unwrap(),
            InputEvent::Gamepad(GamepadEvent {
                source: EventSource::Int(1),
                control: GamepadControlEvent::Axis2D(GamepadAxis2DEvent {
                    index: 42,
                    value: Vec2::new(0.2, -0.2),
                }),
            })
        );
    }
}
