use serde::{Serialize, Deserialize};

/// A keyboard/controller input event, as generated by the frontend in "Legacy Mode" (or the old website).
#[derive(Debug, Serialize, Deserialize, PartialEq, Eq, Clone, Copy)]
pub struct LegacyInputEvent {
    #[serde(rename = "src")]
    pub source: i32,
    pub key: Option<i32>,
    #[serde(rename = "btn")]
    pub button: Option<i32>,
    #[serde(rename = "dwn")]
    pub is_down: bool,
}
